// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/ironclaw.proto

package ironclawpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DeviceId            string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProcessId           int32                  `protobuf:"varint,3,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	PodId               string                 `protobuf:"bytes,4,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	Kind                uint32                 `protobuf:"varint,5,opt,name=kind,proto3" json:"kind,omitempty"`
	ObservedAtUnixNanos int64                  `protobuf:"varint,6,opt,name=observed_at_unix_nanos,json=observedAtUnixNanos,proto3" json:"observed_at_unix_nanos,omitempty"`
	LatencyNanos        int64                  `protobuf:"varint,7,opt,name=latency_nanos,json=latencyNanos,proto3" json:"latency_nanos,omitempty"`
	Bytes               int64                  `protobuf:"varint,8,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Failed              bool                   `protobuf:"varint,9,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_ironclaw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ironclaw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_ironclaw_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *Event) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *Event) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Event) GetObservedAtUnixNanos() int64 {
	if x != nil {
		return x.ObservedAtUnixNanos
	}
	return 0
}

func (x *Event) GetLatencyNanos() int64 {
	if x != nil {
		return x.LatencyNanos
	}
	return 0
}

func (x *Event) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Event) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type Batch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeviceId           string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CreatedAtUnixNanos int64                  `protobuf:"varint,2,opt,name=created_at_unix_nanos,json=createdAtUnixNanos,proto3" json:"created_at_unix_nanos,omitempty"`
	Events             []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_ironclaw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ironclaw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_ironclaw_proto_rawDescGZIP(), []int{1}
}

func (x *Batch) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Batch) GetCreatedAtUnixNanos() int64 {
	if x != nil {
		return x.CreatedAtUnixNanos
	}
	return 0
}

func (x *Batch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type AggregateWindow struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ProcessId            int32                  `protobuf:"varint,3,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	PodId                string                 `protobuf:"bytes,4,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	WindowId             int64                  `protobuf:"varint,5,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Sequence             int64                  `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	WindowStartUnixNanos int64                  `protobuf:"varint,7,opt,name=window_start_unix_nanos,json=windowStartUnixNanos,proto3" json:"window_start_unix_nanos,omitempty"`
	WindowEndUnixNanos   int64                  `protobuf:"varint,8,opt,name=window_end_unix_nanos,json=windowEndUnixNanos,proto3" json:"window_end_unix_nanos,omitempty"`
	Count                int64                  `protobuf:"varint,9,opt,name=count,proto3" json:"count,omitempty"`
	ErrorCount           int64                  `protobuf:"varint,10,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	Bytes                int64                  `protobuf:"varint,11,opt,name=bytes,proto3" json:"bytes,omitempty"`
	P95Nanos             int64                  `protobuf:"varint,12,opt,name=p95_nanos,json=p95Nanos,proto3" json:"p95_nanos,omitempty"`
	P99Nanos             int64                  `protobuf:"varint,13,opt,name=p99_nanos,json=p99Nanos,proto3" json:"p99_nanos,omitempty"`
	MaxNanos             int64                  `protobuf:"varint,14,opt,name=max_nanos,json=maxNanos,proto3" json:"max_nanos,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AggregateWindow) Reset() {
	*x = AggregateWindow{}
	mi := &file_proto_ironclaw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateWindow) ProtoMessage() {}

func (x *AggregateWindow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ironclaw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateWindow.ProtoReflect.Descriptor instead.
func (*AggregateWindow) Descriptor() ([]byte, []int) {
	return file_proto_ironclaw_proto_rawDescGZIP(), []int{2}
}

func (x *AggregateWindow) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AggregateWindow) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AggregateWindow) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *AggregateWindow) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *AggregateWindow) GetWindowId() int64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

func (x *AggregateWindow) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AggregateWindow) GetWindowStartUnixNanos() int64 {
	if x != nil {
		return x.WindowStartUnixNanos
	}
	return 0
}

func (x *AggregateWindow) GetWindowEndUnixNanos() int64 {
	if x != nil {
		return x.WindowEndUnixNanos
	}
	return 0
}

func (x *AggregateWindow) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregateWindow) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *AggregateWindow) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *AggregateWindow) GetP95Nanos() int64 {
	if x != nil {
		return x.P95Nanos
	}
	return 0
}

func (x *AggregateWindow) GetP99Nanos() int64 {
	if x != nil {
		return x.P99Nanos
	}
	return 0
}

func (x *AggregateWindow) GetMaxNanos() int64 {
	if x != nil {
		return x.MaxNanos
	}
	return 0
}

var File_proto_ironclaw_proto protoreflect.FileDescriptor

const file_proto_ironclaw_proto_rawDesc = "" +
	"\n" +
	"\x14proto/ironclaw.proto\x12\vironclaw.v1\"\x8f\x02\n" +
	"\x05Event\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x03 \x01(\x05R\tprocessId\x12\x15\n" +
	"\x06pod_id\x18\x04 \x01(\tR\x05podId\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\rR\x04kind\x123\n" +
	"\x16observed_at_unix_nanos\x18\x06 \x01(\x03R\x13observedAtUnixNanos\x12#\n" +
	"\rlatency_nanos\x18\a \x01(\x03R\flatencyNanos\x12\x14\n" +
	"\x05bytes\x18\b \x01(\x03R\x05bytes\x12\x16\n" +
	"\x06failed\x18\t \x01(\bR\x06failed\"\x83\x01\n" +
	"\x05Batch\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x121\n" +
	"\x15created_at_unix_nanos\x18\x02 \x01(\x03R\x12createdAtUnixNanos\x12*\n" +
	"\x06events\x18\x03 \x03(\v2\x12.ironclaw.v1.EventR\x06events\"\xc4\x03\n" +
	"\x0fAggregateWindow\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x03 \x01(\x05R\tprocessId\x12\x15\n" +
	"\x06pod_id\x18\x04 \x01(\tR\x05podId\x12\x1b\n" +
	"\twindow_id\x18\x05 \x01(\x03R\bwindowId\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x03R\bsequence\x125\n" +
	"\x17window_start_unix_nanos\x18\a \x01(\x03R\x14windowStartUnixNanos\x121\n" +
	"\x15window_end_unix_nanos\x18\b \x01(\x03R\x12windowEndUnixNanos\x12\x14\n" +
	"\x05count\x18\t \x01(\x03R\x05count\x12\x1f\n" +
	"\verror_count\x18\n" +
	" \x01(\x03R\n" +
	"errorCount\x12\x14\n" +
	"\x05bytes\x18\v \x01(\x03R\x05bytes\x12\x1b\n" +
	"\tp95_nanos\x18\f \x01(\x03R\bp95Nanos\x12\x1b\n" +
	"\tp99_nanos\x18\r \x01(\x03R\bp99Nanos\x12\x1b\n" +
	"\tmax_nanos\x18\x0e \x01(\x03R\bmaxNanosB;Z9github.com/ironclaw/mcp-ironclaw/internal/wire/ironclawpbb\x06proto3"

var (
	file_proto_ironclaw_proto_rawDescOnce sync.Once
	file_proto_ironclaw_proto_rawDescData []byte
)

func file_proto_ironclaw_proto_rawDescGZIP() []byte {
	file_proto_ironclaw_proto_rawDescOnce.Do(func() {
		file_proto_ironclaw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ironclaw_proto_rawDesc), len(file_proto_ironclaw_proto_rawDesc)))
	})
	return file_proto_ironclaw_proto_rawDescData
}

var file_proto_ironclaw_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_ironclaw_proto_goTypes = []any{
	(*Event)(nil),           // 0: ironclaw.v1.Event
	(*Batch)(nil),           // 1: ironclaw.v1.Batch
	(*AggregateWindow)(nil), // 2: ironclaw.v1.AggregateWindow
}
var file_proto_ironclaw_proto_depIdxs = []int32{
	0, // 0: ironclaw.v1.Batch.events:type_name -> ironclaw.v1.Event
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ironclaw_proto_init() }
func file_proto_ironclaw_proto_init() {
	if File_proto_ironclaw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ironclaw_proto_rawDesc), len(file_proto_ironclaw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ironclaw_proto_goTypes,
		DependencyIndexes: file_proto_ironclaw_proto_depIdxs,
		MessageInfos:      file_proto_ironclaw_proto_msgTypes,
	}.Build()
	File_proto_ironclaw_proto = out.File
	file_proto_ironclaw_proto_goTypes = nil
	file_proto_ironclaw_proto_depIdxs = nil
}
